import { Injectable } from '@angular/core';
import { Observable, of } from 'rxjs';
import { Product } from '../models/product.model';

const MOCK_PRODUCTS: Product[] = [
  {
    id: 'volumetric-flask',
    name: 'Volumetric Flask',
    shortName: 'Volumetric Flask',
    category: 'volumetric',
    material: '3.3 Borosilicate Glass',
    classType: 'Standard',
    sizes: ['100 mL', '250 mL', '500 mL', '1000 mL'],
    tolerance: '±0.08–0.40 mL at 20°C',
    thermalSpec: 'Thermal Shock Resistance ΔT ≥ 120°C',
    standard: 'Conforms to ASTM E288',
    specs: [
      { label: 'Material', value: '3.3 Borosilicate' },
      { label: 'Accuracy', value: 'Standard' },
      { label: 'Tolerance', value: '±0.08–0.40 mL' },
      { label: 'Temp Ref', value: '20°C' },
    ],
    description: 'Precision-calibrated one-mark volumetric flasks for critical analytical work. Batch-level quality validation with traceable manufacturing processes. Class A grade available on request.',
    featured: true,
    silhouette: 'volumetric-flask',
    iconUrl: 'assets/products/volumetric-flask.svg',
  },
  {
    id: 'graduated-burette',
    name: 'Graduated Burette',
    shortName: 'Burette',
    category: 'analytical',
    material: '3.3 Borosilicate Glass',
    classType: 'Standard',
    sizes: ['25 mL', '50 mL'],
    tolerance: '±0.03–0.05 mL at 20°C',
    thermalSpec: 'Thermal Shock Resistance ΔT ≥ 120°C',
    standard: 'Conforms to ASTM E287',
    specs: [
      { label: 'Material', value: '3.3 Borosilicate' },
      { label: 'Accuracy', value: 'Standard' },
      { label: 'Tolerance', value: '±0.03–0.05 mL' },
      { label: 'Stopcock', value: 'PTFE Plug' },
    ],
    description: 'Precision-bore burettes with PTFE stopcock for accurate titrimetric analysis. Manufactured to international dimensional tolerances. Class A grade available on request.',
    featured: true,
    silhouette: 'burette',
    iconUrl: 'assets/products/burette.svg',
  },
  {
    id: 'liebig-condenser',
    name: 'Liebig Condenser',
    shortName: 'Liebig Condenser',
    category: 'distillation',
    material: '3.3 Borosilicate Glass',
    classType: 'Standard',
    sizes: ['300 mm', '400 mm', '500 mm'],
    tolerance: 'Jacket OD ±0.5 mm',
    thermalSpec: 'Thermal Shock Resistance ΔT ≥ 120°C',
    standard: 'Conforms to DIN 12331',
    specs: [
      { label: 'Material', value: '3.3 Borosilicate' },
      { label: 'Jacket', value: 'Water-cooled' },
      { label: 'Joint', value: 'Ground Glass' },
      { label: 'Standard', value: 'DIN 12331' },
    ],
    description: 'High-efficiency water-cooled condensers with precision-ground glass joints. Engineered for distillation and reflux applications.',
    featured: true,
    silhouette: 'condenser',
    iconUrl: 'assets/products/liebig-condenser.svg',
  },
  {
    id: 'kjeldahl-flask',
    name: 'Kjeldahl Digestion Flask',
    shortName: 'Kjeldahl Flask',
    category: 'specialty',
    material: '3.3 Borosilicate Glass',
    classType: 'Standard',
    sizes: ['250 mL', '500 mL', '800 mL'],
    tolerance: 'Capacity ±2%',
    thermalSpec: 'Thermal Shock Resistance ΔT ≥ 120°C',
    standard: 'Conforms to ASTM E438',
    specs: [
      { label: 'Material', value: '3.3 Borosilicate' },
      { label: 'Neck', value: 'Long narrow neck' },
      { label: 'Base', value: 'Pear-shaped' },
      { label: 'Standard', value: 'ASTM E438' },
    ],
    description: 'Long-neck pear-shaped flasks for nitrogen determination by Kjeldahl method. Resistant to concentrated acids and alkalis.',
    featured: true,
    silhouette: 'kjeldahl-flask',
    iconUrl: 'assets/products/kjeldahl-flask.svg',
  },
  {
    id: 'griffin-beaker',
    name: 'Griffin Beaker',
    shortName: 'Beaker',
    category: 'general',
    material: '3.3 Borosilicate Glass',
    classType: 'Standard',
    sizes: ['50 mL', '100 mL', '250 mL', '500 mL', '1000 mL', '2000 mL', '5000 mL'],
    tolerance: 'Graduated ±5%',
    thermalSpec: 'Thermal Shock Resistance ΔT ≥ 120°C',
    standard: 'Conforms to ASTM E960',
    specs: [
      { label: 'Material', value: '3.3 Borosilicate' },
      { label: 'Form', value: 'Griffin (Low)' },
      { label: 'Graduation', value: 'Screen-printed' },
      { label: 'Spout', value: 'Angled pour spout' },
    ],
    description: 'Standard-form beakers with uniform wall thickness and calibrated graduation marks for general laboratory use.',
    featured: false,
  },
  {
    id: 'erlenmeyer-flask',
    name: 'Erlenmeyer Conical Flask',
    shortName: 'Erlenmeyer Flask',
    category: 'general',
    material: '3.3 Borosilicate Glass',
    classType: 'Standard',
    sizes: ['100 mL', '250 mL', '500 mL', '1000 mL', '2000 mL'],
    tolerance: 'Graduated ±5%',
    thermalSpec: 'Thermal Shock Resistance ΔT ≥ 120°C',
    standard: 'Conforms to ASTM E1404',
    specs: [
      { label: 'Material', value: '3.3 Borosilicate' },
      { label: 'Neck', value: 'Narrow mouth' },
      { label: 'Graduation', value: 'Screen-printed' },
    ],
    description: 'Conical flasks for mixing, heating, and titration. Narrow mouth minimizes evaporation during extended operations.',
    featured: false,
  },
  {
    id: 'petri-dish',
    name: 'Borosilicate Petri Dish',
    shortName: 'Petri Dish',
    category: 'general',
    material: '3.3 Borosilicate Glass',
    classType: 'Standard',
    sizes: ['60 mm', '90 mm', '120 mm'],
    tolerance: 'Diameter ±0.5 mm',
    thermalSpec: 'Thermal Shock Resistance ΔT ≥ 120°C',
    standard: 'Conforms to ASTM E438',
    specs: [
      { label: 'Material', value: '3.3 Borosilicate' },
      { label: 'Lid', value: 'Matching cover' },
      { label: 'Autoclavable', value: 'Yes' },
    ],
    description: 'Flat-bottomed borosilicate petri dishes with precision-fit lids. Autoclavable for sterile cell culture and microbiology.',
    featured: false,
  },
  {
    id: 'test-tube',
    name: 'Borosilicate Test Tube',
    shortName: 'Test Tube',
    category: 'general',
    material: '3.3 Borosilicate Glass',
    classType: 'Standard',
    sizes: ['10×75 mm', '13×100 mm', '16×150 mm', '18×180 mm', '25×200 mm'],
    tolerance: 'OD ±0.3 mm',
    thermalSpec: 'Thermal Shock Resistance ΔT ≥ 120°C',
    standard: 'Conforms to ASTM E438',
    specs: [
      { label: 'Material', value: '3.3 Borosilicate' },
      { label: 'Rim', value: 'Fire-polished' },
      { label: 'Base', value: 'Round bottom' },
    ],
    description: 'Fire-polished borosilicate test tubes with uniform bore and smooth rim for safe handling.',
    featured: false,
  },
  {
    id: 'sep-funnel',
    name: 'Separatory Funnel',
    shortName: 'Sep Funnel',
    category: 'specialty',
    material: '3.3 Borosilicate Glass',
    classType: 'Standard',
    sizes: ['60 mL', '125 mL', '250 mL', '500 mL', '1000 mL', '2000 mL'],
    tolerance: 'Graduated ±5%',
    thermalSpec: 'Thermal Shock Resistance ΔT ≥ 120°C',
    standard: 'Conforms to ASTM E438',
    specs: [
      { label: 'Material', value: '3.3 Borosilicate' },
      { label: 'Stopcock', value: 'PTFE plug' },
      { label: 'Form', value: 'Pear-shaped' },
    ],
    description: 'Pear-shaped separatory funnels with PTFE stopcock for solvent extraction and liquid-liquid separation.',
    featured: false,
  },
  {
    id: 'rbf',
    name: 'Round-Bottom Flask',
    shortName: 'RB Flask',
    category: 'distillation',
    material: '3.3 Borosilicate Glass',
    classType: 'Standard',
    sizes: ['50 mL', '100 mL', '250 mL', '500 mL', '1000 mL', '2000 mL', '5000 mL'],
    tolerance: 'Capacity ±2%',
    thermalSpec: 'Thermal Shock Resistance ΔT ≥ 120°C',
    standard: 'Conforms to ASTM E438',
    specs: [
      { label: 'Material', value: '3.3 Borosilicate' },
      { label: 'Joint', value: '24/40 ground glass' },
      { label: 'Wall', value: 'Uniform thickness' },
    ],
    description: 'Uniform-wall round-bottom flasks with standard-taper ground glass joints for distillation and reflux assemblies.',
    featured: false,
  },
  {
    id: 'grad-cylinder-b',
    name: 'Class B Graduated Cylinder',
    shortName: 'Graduated Cylinder',
    category: 'volumetric',
    material: '3.3 Borosilicate Glass',
    classType: 'Class B',
    sizes: ['10 mL', '25 mL', '50 mL', '100 mL', '250 mL', '500 mL', '1000 mL', '2000 mL'],
    tolerance: '±0.1–5 mL at 20°C',
    thermalSpec: 'Thermal Shock Resistance ΔT ≥ 120°C',
    standard: 'Conforms to ASTM E1272',
    specs: [
      { label: 'Material', value: '3.3 Borosilicate' },
      { label: 'Accuracy', value: 'Class B' },
      { label: 'Tolerance', value: '±0.1–5 mL' },
      { label: 'Base', value: 'Hexagonal moulded' },
    ],
    description: 'Hexagonal-base graduated cylinders for routine volume measurements. Moulded markings for long-term legibility.',
    featured: false,
  },
  {
    id: 'reagent-bottle',
    name: 'Reagent Bottle',
    shortName: 'Reagent Bottle',
    category: 'general',
    material: '3.3 Borosilicate Glass',
    classType: 'Standard',
    sizes: ['60 mL', '125 mL', '250 mL', '500 mL', '1000 mL', '2500 mL'],
    tolerance: 'Neck GL45 ±0.2 mm',
    thermalSpec: 'Thermal Shock Resistance ΔT ≥ 120°C',
    standard: 'Conforms to DIN 12331',
    specs: [
      { label: 'Material', value: '3.3 Borosilicate' },
      { label: 'Neck', value: 'GL45 thread' },
      { label: 'Variants', value: 'Clear & Amber' },
    ],
    description: 'Wide-mouth GL45 reagent bottles in clear and amber glass for light-sensitive reagent storage.',
    featured: false,
  },
  {
    id: 'watch-glass',
    name: 'Watch Glass',
    shortName: 'Watch Glass',
    category: 'general',
    material: '3.3 Borosilicate Glass',
    classType: 'Standard',
    sizes: ['60 mm', '75 mm', '100 mm', '120 mm', '150 mm'],
    tolerance: 'Diameter ±0.5 mm',
    thermalSpec: 'Thermal Shock Resistance ΔT ≥ 120°C',
    standard: 'Conforms to ASTM E438',
    specs: [
      { label: 'Material', value: '3.3 Borosilicate' },
      { label: 'Edge', value: 'Fire-polished' },
      { label: 'Form', value: 'Concave disc' },
    ],
    description: 'Concave borosilicate watch glasses for evaporation, precipitation observation, and beaker covers.',
    featured: false,
  },
  {
    id: 'distillation-flask',
    name: 'Distillation Flask',
    shortName: 'Distillation Flask',
    category: 'distillation',
    material: '3.3 Borosilicate Glass',
    classType: 'Standard',
    sizes: ['500 mL', '1000 mL', '2000 mL'],
    tolerance: 'Capacity ±2%',
    thermalSpec: 'Thermal Shock Resistance ΔT ≥ 120°C',
    standard: 'Conforms to ASTM E438',
    specs: [
      { label: 'Material', value: '3.3 Borosilicate' },
      { label: 'Side arm', value: '75° angled' },
      { label: 'Joint', value: '24/40 ground glass' },
    ],
    description: 'Flat-bottom distillation flasks with angled side arm and ground glass joints for distillation assemblies.',
    featured: false,
  },
];

@Injectable({ providedIn: 'root' })
export class ProductsService {
  getAll(): Observable<Product[]> {
    return of(MOCK_PRODUCTS);
  }

  getFeatured(): Observable<Product[]> {
    return of(MOCK_PRODUCTS.filter(p => p.featured));
  }

  getById(id: string): Observable<Product | undefined> {
    return of(MOCK_PRODUCTS.find(p => p.id === id));
  }
}
